name: unittests
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    name: Unittests
    steps:
      - uses: actions/checkout@v2
      - name: Install System dependencies
        run: sudo apt update && sudo apt install -y $(echo $(cat requirements/ubuntu.txt))
      - name: Docker login
        run: docker login -u mmontao -p ${{ secrets.DOCKERHUB_PASS  }}
      - name: Build Docker Image
        run: docker build -t mmontao/clcs:${GITHUB_REF#refs/*/} .
      - name: Docker push
        run: docker push mmontao/clcs:${GITHUB_REF#refs/*/}
      - name: Docker logout
        run: docker logout